version: "3"

services:
    gateway-service:
        build:
            context: ./gateway-nodejs-service
        volumes:
            - ./gateway-nodejs-service:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 5000:8080
        environment:
            - PORT=8080

    indeed-service:
        build: ./indeed-service
        volumes:
            - ./indeed-service:/usr/src/app
        ports:
            - 5001:8080
        environment:
            - PORT=8080

    linkedin-service:
        build: ./linkedin-service
        volumes:
            - ./linkedin-service:/usr/src/app
        ports:
            - 5002:8080
        environment:
            - PORT=8080

    monster-service:
        build: ./monster-service
        volumes:
            - ./monster-service:/usr/src/app
        ports:
            - 5003:8080
        environment:
            - PORT=8080

    model-service:
        build: ./model-service
        volumes:
            - ./model-service:/usr/src/app
        ports:
            - 6000:8080
        environment:
            - PORT=8080
            
            
