 steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/indeed-service:$COMMIT_SHA', './indeed-service']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/indeed-service:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'indeed-service'
   - '--image'
   - 'gcr.io/$PROJECT_ID/indeed-service:$COMMIT_SHA'
   - '--region'
   - 'us-east1'
   - '--platform'
   - 'managed'
 images:
 - 'gcr.io/$PROJECT_ID/indeed-service:$COMMIT_SHA'
